name: Reporte de bug
description: Creaci贸n de un reporte de bug para ayudarnos a mejorar nuestro software.
title: "[Bug]: "
labels: [Bug]
#assignees: [joseatrejos, claudiobo]
body:
- type: markdown
  attributes:
    value: |
      Agradecemos de antemano su tiempo invertido para llenar este reporte.
- type: textarea
  attributes:
    label: Fecha de ejecuci贸n de la prueba 
    description: Fecha exacta en la que se realiz贸 la prueba
    placeholder: |
      Fecha
  validations:
    required: true
- type: textarea
  attributes:
    label: Descripci贸n del error 
    description: Una descripci贸n concisa de lo que se experiment贸 durante la prueba.
    placeholder: |
      Cuando hago <X>, sucede <Y>
  validations:
    required: true
- type: textarea
  attributes:
    label: Para reproducirlo
    description: Pasos para replicar el error, con im谩genes en caso de considerarse necesario.
    placeholder: |
      1. Ir a '...'
      2. Click en '....'
      3. Scroll down en '....'
      4. error
  validations:
    required: true
- type: textarea
  attributes:
    label: Mensaje de error
    description: El mensaje de error observado en el sistema si aplica.
    placeholder: |
      Mensaje de error
  validations:
    required: false
- type: textarea
  attributes:
    label: Enlace de la p谩gina donde se present贸 el error
    description: Enlace de la p谩gina donde se present贸 el error, si aplica.
    placeholder: |
      Enlace
  validations:
    required: false
- type: textarea
  attributes:
    label: Comportamiento esperado
    description: Una descripci贸n concisa del comportamiento que se esperaba del sistema.
    placeholder: |
      Lo que espero que suceda es <Z>
  validations:
    required: true
- type: dropdown
  id: entorno
  attributes:
    label: Entorno
    options:
      - Entorno de desarrollo
      - Entorno de Staging/UAT/Pruebas
      - Entorno productivo
  validations:
    required: true
- type: dropdown
  id: browser
  attributes:
    label: Browser
    options:
      - Google Chrome
      - Mozilla Firefox
      - Safari
      - Opera.
      - Microsoft Edge.
      - Otro.
    required: true
- type: textarea
  id: version
  attributes:
    label: Version
    placeholder: |
      Versi贸n del sistema.
  validations:
    required: true
- type: textarea
  id: user
  attributes:
    label: Usuario y roles
    description: Usuario con el que se realiz贸 la prueba y roles con los que cuenta dicho usuario.
    placeholder: |
      Usuario y roles.
  validations:
    required: true
