name: Solicitud de requerimiento
description: Alta de solicitud para un ajuste menor o un nuevo requerimiento menor.
title: "[Solicitud menor]: "
labels: [Request]

body:
- type: markdown
  attributes:
    value: |
      Agradecemos de antemano su tiempo invertido para llenar esta solicitud.

- type: textarea
  attributes:
    label: Descripci贸n de la solicitud 
    description: Solicitud de desarrollo que se requiere
    placeholder: |
      Descripci贸n de la solicitud.
  validations:
    required: true

- type: textarea
  id: user
  attributes:
    label: Usuarios involucrados
    description: Usuarios que realizar谩n cada acci贸n.
    placeholder: |
      Usuarios y acciones de cada uno.

- type: textarea
  attributes:
    label: Contexto adicional
    description: Contexto adicional que se considere necesario para la comprensi贸n del error.
    placeholder: |
      Contexto adicional.
  validations:
    required: false
